package main.java.com.constants;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ChampList {
	private String[] champList;
	private Map<String, Integer> champToID;
	public ChampList(){
		champToID = new LinkedHashMap<>();
		champToID.put("Aatrox", 266);
		champToID.put("Ahri", 103);
		champToID.put("Akali", 84);
		champToID.put("Alistar", 12);
		champToID.put("Amumu", 32);
		champToID.put("Anivia", 34);
		champToID.put("Annie", 1);
		champToID.put("Ashe", 22);
		champToID.put("Aurelion Sol", 136);
		champToID.put("Azir", 268);
		champToID.put("Bard", 432);
		champToID.put("Blitzcrank", 53);
		champToID.put("Brand", 63);
		champToID.put("Braum", 201);
		champToID.put("Caitlyn", 51);
		champToID.put("Camille", 164);
		champToID.put("Cassiopeia", 69);
		champToID.put("Chogath", 31);
		champToID.put("Corki", 42);
		champToID.put("Darius", 122);
		champToID.put("Diana", 131);
		champToID.put("DrMundo", 36);
		champToID.put("Draven", 119);
		champToID.put("Ekko", 245);
		champToID.put("Elise", 60);
		champToID.put("Evelynn", 28);
		champToID.put("Ezreal", 81);
		champToID.put("FiddleSticks", 9);
		champToID.put("Fiora", 114);
		champToID.put("Fizz", 105);
		champToID.put("Galio", 3);
		champToID.put("Gangplank", 41);
		champToID.put("Garen", 86);
		champToID.put("Gnar", 150);
		champToID.put("Gragas", 79);
		champToID.put("Graves", 104);
		champToID.put("Hecarim", 120);
		champToID.put("Heimerdinger", 74);
		champToID.put("Illaoi", 420);
		champToID.put("Irelia", 39);
		champToID.put("Ivern", 427);
		champToID.put("Janna", 40);
		champToID.put("Jax", 24);
		champToID.put("Jayce", 126);
		champToID.put("Jhin", 202);
		champToID.put("Jinx", 222);
		champToID.put("JrvanIV", 59);
		champToID.put("Kai'sa", 145);
		champToID.put("Kalista", 429);
		champToID.put("Karma", 43);
		champToID.put("Karthus", 30);
		champToID.put("Kassadin", 38);
		champToID.put("Katarina", 55);
		champToID.put("Kayle", 10);
		champToID.put("Kayn", 141);
		champToID.put("Kennen", 85);
		champToID.put("Khazix", 121);
		champToID.put("Kindred", 203);
		champToID.put("Kled", 240);
		champToID.put("KogMaw", 96);
		champToID.put("Leblanc", 7);
		champToID.put("LeeSin", 64);
		champToID.put("Leona", 89);
		champToID.put("Lissandra", 127);
		champToID.put("Lucian", 236);
		champToID.put("Lulu", 117);
		champToID.put("Lux", 99);
		champToID.put("Malphite", 54);
		champToID.put("Malzahar", 90);
		champToID.put("Maokai", 57);
		champToID.put("MasterYi", 11);
		champToID.put("MissFortune", 21);
		champToID.put("Mordekaiser", 82);
		champToID.put("Morgana", 25);
		champToID.put("Nami", 267);
		champToID.put("Nasus", 75);
		champToID.put("Nautilus", 111);
		champToID.put("Neeko", 518);
		champToID.put("Nidalee", 76);
		champToID.put("Nocturne", 56);
		champToID.put("Nunu", 20);
		champToID.put("Olaf", 2);
		champToID.put("Orianna", 61);
		champToID.put("Ornn", 516);
		champToID.put("Pantheon", 80);
		champToID.put("Poppy", 78);
		champToID.put("Pyke", 555);
		champToID.put("Qiyana", 246);
		champToID.put("Quinn", 133);
		champToID.put("Rakan", 497);
		champToID.put("Rammus", 33);
		champToID.put("RekSai", 421);
		champToID.put("Renekton", 58);
		champToID.put("Rengar", 107);
		champToID.put("Riven", 92);
		champToID.put("Rumble", 68);
		champToID.put("Ryze", 13);
		champToID.put("Sejuani", 113);
		champToID.put("Shaco", 35);
		champToID.put("Shen", 98);
		champToID.put("Shyvana", 102);
		champToID.put("Singed", 27);
		champToID.put("Sion", 14);
		champToID.put("Sivir", 15);
		champToID.put("Skarner", 72);
		champToID.put("Sona", 37);
		champToID.put("Soraka", 16);
		champToID.put("Swain", 50);
		champToID.put("Sylas", 517);
		champToID.put("Syndra", 134);
		champToID.put("TahmKench", 223);
		champToID.put("Taliyah", 163);
		champToID.put("Talon", 91);
		champToID.put("Taric", 44);
		champToID.put("Teemo", 17);
		champToID.put("Thresh", 412);
		champToID.put("Tristana", 18);
		champToID.put("Trundle", 48);
		champToID.put("Tryndamere", 23);
		champToID.put("TwistedFate", 4);
		champToID.put("Twitch", 29);
		champToID.put("Udyr", 77);
		champToID.put("Urgot", 6);
		champToID.put("Varus", 110);
		champToID.put("Vayne", 67);
		champToID.put("Veigar", 45);
		champToID.put("Velkoz", 161);
		champToID.put("Vi", 254);
		champToID.put("Viktor", 112);
		champToID.put("Vladimir", 8);
		champToID.put("Volibear", 106);
		champToID.put("Warwick", 19);
		champToID.put("Wukong", 62);
		champToID.put("Xayah", 498);
		champToID.put("Xerath", 101);
		champToID.put("XinZhao", 5);
		champToID.put("Yasuo", 157);
		champToID.put("Yorick", 83);
		champToID.put("Yuumi", 350);
		champToID.put("Zac", 154);
		champToID.put("Zed", 238);
		champToID.put("Ziggs", 115);
		champToID.put("Zilean", 26);
		champToID.put("Zoe", 142);
		champToID.put("Zyra", 143);
		
		champList = new String[1000];
		champList[266] = "Aatrox";
		champList[103] = "Ahri";
		champList[84] = "Akali";
		champList[12] = "Alistar";
		champList[32] = "Amumu";
		champList[34] = "Anivia";
		champList[1] = "Annie";
		champList[22] = "Ashe";
		champList[136] = "Aurelion Sol";
		champList[268] = "Azir";
		champList[432] = "Bard";
		champList[53] = "Blitzcrank";
		champList[63] = "Brand";
		champList[201] = "Braum";
		champList[51] = "Caitlyn";
		champList[164] = "Camille";
		champList[69] = "Cassiopeia";
		champList[31] = "Chogath";
		champList[42] = "Corki";
		champList[122] = "Darius";
		champList[131] = "Diana";
		champList[119] = "Draven";
		champList[36] = "DrMundo";
		champList[245] = "Ekko";
		champList[60] = "Elise";
		champList[28] = "Evelynn";
		champList[81] = "Ezreal";
		champList[9] = "FiddleSticks";
		champList[114] = "Fiora";
		champList[105] = "Fizz";
		champList[3] = "Galio";
		champList[41] = "Gangplank";
		champList[86] = "Garen";
		champList[150] = "Gnar";
		champList[79] = "Gragas";
		champList[104] = "Graves";
		champList[120] = "Hecarim";
		champList[74] = "Heimerdinger";
		champList[420] = "Illaoi";
		champList[39] = "Irelia";
		champList[427] = "Ivern";
		champList[40] = "Janna";
		champList[59] = "JrvanIV";
		champList[24] = "Jax";
		champList[126] = "Jayce";
		champList[202] = "Jhin";
		champList[222] = "Jinx";
		champList[145] = "Kai'sa";
		champList[429] = "Kalista";
		champList[43] = "Karma";
		champList[30] = "Karthus";
		champList[38] = "Kassadin";
		champList[55] = "Katarina";
		champList[10] = "Kayle";
		champList[141] = "Kayn";
		champList[85] = "Kennen";
		champList[121] = "Khazix";
		champList[203] = "Kindred";
		champList[240] = "Kled";
		champList[96] = "KogMaw";
		champList[7] = "Leblanc";
		champList[64] = "LeeSin";
		champList[89] = "Leona";
		champList[127] = "Lissandra";
		champList[236] = "Lucian";
		champList[117] = "Lulu";
		champList[99] = "Lux";
		champList[54] = "Malphite";
		champList[90] = "Malzahar";
		champList[57] = "Maokai";
		champList[11] = "MasterYi";
		champList[21] = "MissFortune";
		champList[62] = "Wukong";
		champList[82] = "Mordekaiser";
		champList[25] = "Morgana";
		champList[267] = "Nami";
		champList[75] = "Nasus";
		champList[111] = "Nautilus";
		champList[518] = "Neeko";
		champList[76] = "Nidalee";
		champList[56] = "Nocturne";
		champList[20] = "Nunu";
		champList[2] = "Olaf";
		champList[61] = "Orianna";
		champList[516] = "Ornn";
		champList[80] = "Pantheon";
		champList[78] = "Poppy";
		champList[555] = "Pyke";
		champList[133] = "Quinn";
		champList[246] = "Qiyana";
		champList[33] = "Rammus";
		champList[497] = "Rakan";
		champList[421] = "RekSai";
		champList[58] = "Renekton";
		champList[107] = "Rengar";
		champList[92] = "Riven";
		champList[68] = "Rumble";
		champList[13] = "Ryze";
		champList[113] = "Sejuani";
		champList[35] = "Shaco";
		champList[98] = "Shen";
		champList[102] = "Shyvana";
		champList[27] = "Singed";
		champList[14] = "Sion";
		champList[15] = "Sivir";
		champList[72] = "Skarner";
		champList[37] = "Sona";
		champList[16] = "Soraka";
		champList[50] = "Swain";
		champList[517] = "Sylas";
		champList[134] = "Syndra";
		champList[223] = "TahmKench";
		champList[163] = "Taliyah";
		champList[91] = "Talon";
		champList[44] = "Taric";
		champList[17] = "Teemo";
		champList[412] = "Thresh";
		champList[18] = "Tristana";
		champList[48] = "Trundle";
		champList[23] = "Tryndamere";
		champList[4] = "TwistedFate";
		champList[29] = "Twitch";
		champList[77] = "Udyr";
		champList[6] = "Urgot";
		champList[110] = "Varus";
		champList[67] = "Vayne";
		champList[45] = "Veigar";
		champList[161] = "Velkoz";
		champList[254] = "Vi";
		champList[112] = "Viktor";
		champList[8] = "Vladimir";
		champList[106] = "Volibear";
		champList[19] = "Warwick";
		champList[498] = "Xayah";
		champList[101] = "Xerath";
		champList[5] = "XinZhao";
		champList[157] = "Yasuo";
		champList[83] = "Yorick";
		champList[350] = "Yuumi";
		champList[154] = "Zac";
		champList[238] = "Zed";
		champList[115] = "Ziggs";
		champList[26] = "Zilean";
		champList[142] = "Zoe";
		champList[143] = "Zyra";
	}
	public Map<String, Integer> getChampMap(){
		return this.champToID;
	}
	public String[] getChampList(){
		return champList;
	}
}
